//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonEditorV2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JsonEditorV2.Resources.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON 資料檔案編輯器 0.1.
        /// </summary>
        public static string JE_ABOUT_MESSAGE {
            get {
                return ResourceManager.GetString("JE_ABOUT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by KentKaze.
        /// </summary>
        public static string JE_ABOUT_MESSAGE_2 {
            get {
                return ResourceManager.GetString("JE_ABOUT_MESSAGE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關於.
        /// </summary>
        public static string JE_ABOUT_TITLE {
            get {
                return ResourceManager.GetString("JE_ABOUT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空.
        /// </summary>
        public static string JE_BTN_CLEAR_MAIN {
            get {
                return ResourceManager.GetString("JE_BTN_CLEAR_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除.
        /// </summary>
        public static string JE_BTN_DELETE_COLUMN {
            get {
                return ResourceManager.GetString("JE_BTN_DELETE_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        public static string JE_BTN_UPDATE_COLUMN {
            get {
                return ResourceManager.GetString("JE_BTN_UPDATE_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        public static string JE_BTN_UPDATE_MAIN {
            get {
                return ResourceManager.GetString("JE_BTN_UPDATE_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顯示在清單上.
        /// </summary>
        public static string JE_COLUMN_DISPLAY {
            get {
                return ResourceManager.GetString("JE_COLUMN_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外部索引.
        /// </summary>
        public static string JE_COLUMN_FK {
            get {
                return ResourceManager.GetString("JE_COLUMN_FK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是索引.
        /// </summary>
        public static string JE_COLUMN_IS_KEY {
            get {
                return ResourceManager.GetString("JE_COLUMN_IS_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欄位名稱.
        /// </summary>
        public static string JE_COLUMN_NAME {
            get {
                return ResourceManager.GetString("JE_COLUMN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欄位行數.
        /// </summary>
        public static string JE_COLUMN_NUM_OF_ROWS {
            get {
                return ResourceManager.GetString("JE_COLUMN_NUM_OF_ROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欄位型別.
        /// </summary>
        public static string JE_COLUMN_TYPE {
            get {
                return ResourceManager.GetString("JE_COLUMN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}檔案已讀入.
        /// </summary>
        public static string JE_RUN_LOAD_JSON_FILES_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_LOAD_JSON_FILES_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已在&quot;{0}&quot;新建檔案庫.
        /// </summary>
        public static string JE_RUN_NEW_JSON_FILES_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_NEW_JSON_FILES_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此文件已有現存 {0} JSON檔案，是否要清空資料夾.
        /// </summary>
        public static string JE_RUN_NEW_JSON_FILES_Q_1 {
            get {
                return ResourceManager.GetString("JE_RUN_NEW_JSON_FILES_Q_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開新檔案.
        /// </summary>
        public static string JE_RUN_NEW_JSON_FILES_TITLE {
            get {
                return ResourceManager.GetString("JE_RUN_NEW_JSON_FILES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;所有檔案已存檔.
        /// </summary>
        public static string JE_RUN_SAVE_JSON_FILES_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_SAVE_JSON_FILES_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關於.
        /// </summary>
        public static string JE_TMI_ABOUT {
            get {
                return ResourceManager.GetString("JE_TMI_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 增加欄位.
        /// </summary>
        public static string JE_TMI_ADD_COLUMN {
            get {
                return ResourceManager.GetString("JE_TMI_ADD_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關閉所有檔案.
        /// </summary>
        public static string JE_TMI_CLOSE_ALL_FILES {
            get {
                return ResourceManager.GetString("JE_TMI_CLOSE_ALL_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關閉.
        /// </summary>
        public static string JE_TMI_CLOSE_JSON_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_CLOSE_JSON_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除.
        /// </summary>
        public static string JE_TMI_DELETE_JSON_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_DELETE_JSON_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 離開.
        /// </summary>
        public static string JE_TMI_EXIT {
            get {
                return ResourceManager.GetString("JE_TMI_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案.
        /// </summary>
        public static string JE_TMI_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 讀取JSON檔案庫.
        /// </summary>
        public static string JE_TMI_LOAD_JSON_FILES {
            get {
                return ResourceManager.GetString("JE_TMI_LOAD_JSON_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增JSON檔案.
        /// </summary>
        public static string JE_TMI_NEW_JSON_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_NEW_JSON_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建JSON檔案庫.
        /// </summary>
        public static string JE_TMI_NEW_JSON_FILES {
            get {
                return ResourceManager.GetString("JE_TMI_NEW_JSON_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開啟.
        /// </summary>
        public static string JE_TMI_OPEN_JSON_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_OPEN_JSON_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新命名.
        /// </summary>
        public static string JE_TMI_RENAME_JSON_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_RENAME_JSON_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存取JSON檔案庫.
        /// </summary>
        public static string JE_TMI_SAVE_JSON_FILES {
            get {
                return ResourceManager.GetString("JE_TMI_SAVE_JSON_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 掃描JSON檔案庫.
        /// </summary>
        public static string JE_TMI_SCAN_JSON_FILES {
            get {
                return ResourceManager.GetString("JE_TMI_SCAN_JSON_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON 資料檔案編輯器.
        /// </summary>
        public static string JSON_FILE_EDITOR_TITLE {
            get {
                return ResourceManager.GetString("JSON_FILE_EDITOR_TITLE", resourceCulture);
            }
        }
    }
}
