//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonEditorV2.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JsonEditorV2.Resources.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   錯誤回報：KentKaze@hotmail.com に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ABOUT_CONTACT_US {
            get {
                return ResourceManager.GetString("JE_ABOUT_CONTACT_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JSON 資料檔案編輯器 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ABOUT_MESSAGE {
            get {
                return ResourceManager.GetString("JE_ABOUT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作者：日瀨健人 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ABOUT_MESSAGE_2 {
            get {
                return ResourceManager.GetString("JE_ABOUT_MESSAGE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   關於 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ABOUT_TITLE {
            get {
                return ResourceManager.GetString("JE_ABOUT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   清空 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_BTN_CLEAR_COLUMN {
            get {
                return ResourceManager.GetString("JE_BTN_CLEAR_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   清空 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_BTN_CLEAR_MAIN {
            get {
                return ResourceManager.GetString("JE_BTN_CLEAR_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   複製 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_BTN_COPY {
            get {
                return ResourceManager.GetString("JE_BTN_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   複製資料行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_BTN_COPY_LINE {
            get {
                return ResourceManager.GetString("JE_BTN_COPY_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   刪除資料 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_BTN_DELETE_LINE {
            get {
                return ResourceManager.GetString("JE_BTN_DELETE_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編輯選項 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_BTN_EDIT_CHOICES {
            get {
                return ResourceManager.GetString("JE_BTN_EDIT_CHOICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   尋找資料行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_BTN_FIND_LINE {
            get {
                return ResourceManager.GetString("JE_BTN_FIND_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   下移資料行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_BTN_LINE_MOVE_DOWN {
            get {
                return ResourceManager.GetString("JE_BTN_LINE_MOVE_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上移資料行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_BTN_LINE_MOVE_UP {
            get {
                return ResourceManager.GetString("JE_BTN_LINE_MOVE_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_BTN_NEW_GUID {
            get {
                return ResourceManager.GetString("JE_BTN_NEW_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新增資料 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_BTN_NEW_LINE {
            get {
                return ResourceManager.GetString("JE_BTN_NEW_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   重設索引 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_BTN_REGENERATE_KEY {
            get {
                return ResourceManager.GetString("JE_BTN_REGENERATE_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_BTN_UPDATE_COLUMN {
            get {
                return ResourceManager.GetString("JE_BTN_UPDATE_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_BTN_UPDATE_MAIN {
            get {
                return ResourceManager.GetString("JE_BTN_UPDATE_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   值&quot;{0}&quot;已存在 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_CHOICE_DUPLICATE_ITEM {
            get {
                return ResourceManager.GetString("JE_CHOICE_DUPLICATE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新增 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_CHOICES_ADD_ITEM {
            get {
                return ResourceManager.GetString("JE_CHOICES_ADD_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_CHOICES_CONFIRM {
            get {
                return ResourceManager.GetString("JE_CHOICES_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   刪除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_CHOICES_DELETE_ITEM {
            get {
                return ResourceManager.GetString("JE_CHOICES_DELETE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   檔案庫檢查方式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_COB_CHECK_METHOD {
            get {
                return ResourceManager.GetString("JE_COB_CHECK_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全部檢查 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_COB_CHECK_METHOD_FULL_CHECK {
            get {
                return ResourceManager.GetString("JE_COB_CHECK_METHOD_FULL_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不檢查 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_COB_CHECK_METHOD_NO_CHECK {
            get {
                return ResourceManager.GetString("JE_COB_CHECK_METHOD_NO_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   單項無效 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_COB_CHECK_METHOD_ONE_INVALID_CHECK {
            get {
                return ResourceManager.GetString("JE_COB_CHECK_METHOD_ONE_INVALID_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動產生索引值 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_COLUMN_AUTO_GENERATE_KEY {
            get {
                return ResourceManager.GetString("JE_COLUMN_AUTO_GENERATE_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   欄位可選值 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_COLUMN_CHOICES {
            get {
                return ResourceManager.GetString("JE_COLUMN_CHOICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   欄位描述 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_COLUMN_DESCRIPTION {
            get {
                return ResourceManager.GetString("JE_COLUMN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   顯示在清單上 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_COLUMN_DISPLAY {
            get {
                return ResourceManager.GetString("JE_COLUMN_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   外部索引欄位 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_COLUMN_FK_COLUMN {
            get {
                return ResourceManager.GetString("JE_COLUMN_FK_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   外部索引檔案 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_COLUMN_FK_TABLE {
            get {
                return ResourceManager.GetString("JE_COLUMN_FK_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   是索引 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_COLUMN_IS_KEY {
            get {
                return ResourceManager.GetString("JE_COLUMN_IS_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   可以為Null值 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_COLUMN_IS_NULLABLE {
            get {
                return ResourceManager.GetString("JE_COLUMN_IS_NULLABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   唯一值 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_COLUMN_IS_UNIQUE {
            get {
                return ResourceManager.GetString("JE_COLUMN_IS_UNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字最大長度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_COLUMN_MAX_LENGTH {
            get {
                return ResourceManager.GetString("JE_COLUMN_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大值 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_COLUMN_MAX_VALUE {
            get {
                return ResourceManager.GetString("JE_COLUMN_MAX_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最小值 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_COLUMN_MIN_VALUE {
            get {
                return ResourceManager.GetString("JE_COLUMN_MIN_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   欄位名稱 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_COLUMN_NAME {
            get {
                return ResourceManager.GetString("JE_COLUMN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   欄位行數 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_COLUMN_NUM_OF_ROWS {
            get {
                return ResourceManager.GetString("JE_COLUMN_NUM_OF_ROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正則表達式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_COLUMN_REGEX {
            get {
                return ResourceManager.GetString("JE_COLUMN_REGEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   欄位型別 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_COLUMN_TYPE {
            get {
                return ResourceManager.GetString("JE_COLUMN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_DATETIME_DAY {
            get {
                return ResourceManager.GetString("JE_DATETIME_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_DATETIME_HOUR {
            get {
                return ResourceManager.GetString("JE_DATETIME_HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_DATETIME_MINUTE {
            get {
                return ResourceManager.GetString("JE_DATETIME_MINUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_DATETIME_MONTH {
            get {
                return ResourceManager.GetString("JE_DATETIME_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_DATETIME_OK {
            get {
                return ResourceManager.GetString("JE_DATETIME_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_DATETIME_SECOND {
            get {
                return ResourceManager.GetString("JE_DATETIME_SECOND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   年 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_DATETIME_YEAR {
            get {
                return ResourceManager.GetString("JE_DATETIME_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   所有檔案(*.*) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_DIALOG_ALL_FILES {
            get {
                return ResourceManager.GetString("JE_DIALOG_ALL_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV檔案(*.csv) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_DIALOG_CSV_FILE_FULL_NAME {
            get {
                return ResourceManager.GetString("JE_DIALOG_CSV_FILE_FULL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML檔案(*.xml) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_DIALOG_XML_FILE_FULL_NAME {
            get {
                return ResourceManager.GetString("JE_DIALOG_XML_FILE_FULL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無效的JSON檔案&quot;{0}.json&quot;，索引：{1}，欄位數量過多或過少 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ERR_CHILD_COLUMN_COUNT_VARY {
            get {
                return ResourceManager.GetString("JE_ERR_CHILD_COLUMN_COUNT_VARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無效的JSON檔案&quot;{0}.json&quot;，索引：{1}，欄位名稱&quot;{2}&quot;，不正確 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ERR_CHILD_COLUMN_NAME_VARY {
            get {
                return ResourceManager.GetString("JE_ERR_CHILD_COLUMN_NAME_VARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無效的JSON檔案&quot;{0}.json&quot;，索引：{1}，欄位&quot;{2}&quot;順序不正確 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ERR_CHILD_COLUMN_ORDER_VARY {
            get {
                return ResourceManager.GetString("JE_ERR_CHILD_COLUMN_ORDER_VARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無效的JSON檔案&quot;{0}.json&quot;，索引：{1}，欄位&quot;{2}&quot;型別種類太多 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ERR_CHILD_COLUMN_TYPE_VARY {
            get {
                return ResourceManager.GetString("JE_ERR_CHILD_COLUMN_TYPE_VARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無效的JSON檔案&quot;{0}.json&quot;，索引：{1}，子元素非物件 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ERR_CHILD_ELEMENT_NOT_OBJECT {
            get {
                return ResourceManager.GetString("JE_ERR_CHILD_ELEMENT_NOT_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   錯誤發生：&quot;{0}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ERR_DEFAULT_MESSAGE {
            get {
                return ResourceManager.GetString("JE_ERR_DEFAULT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   錯誤 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ERR_DEFAULT_TITLE {
            get {
                return ResourceManager.GetString("JE_ERR_DEFAULT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JSON關聯檔案格式不正確：{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ERR_JSONCONVERT_DESERIALIZE_JFI_FAILED_DEFAULT {
            get {
                return ResourceManager.GetString("JE_ERR_JSONCONVERT_DESERIALIZE_JFI_FAILED_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   檔案&quot;{0}.json&quot;格式不正確：{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ERR_JSONCONVERT_DESERIALIZE_OBJECT_FAILED_DEFAULT {
            get {
                return ResourceManager.GetString("JE_ERR_JSONCONVERT_DESERIALIZE_OBJECT_FAILED_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   讀取JSON關聯檔案&quot;{0}&quot;失敗，請確認檔案是否存在或損毀 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ERR_LOAD_JFI_FILE_FAILED_DEFAULT {
            get {
                return ResourceManager.GetString("JE_ERR_LOAD_JFI_FILE_FAILED_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   讀取檔案失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ERR_LOAD_JSON_FAILED_TITLE {
            get {
                return ResourceManager.GetString("JE_ERR_LOAD_JSON_FAILED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   讀取檔案&quot;{0}&quot;時發生錯誤，請確認檔案是否存在或損毀 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ERR_LOAD_JSON_FILE_FAILED_DEFAULT {
            get {
                return ResourceManager.GetString("JE_ERR_LOAD_JSON_FILE_FAILED_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   發現需要復原的檔案&quot;{0}&quot;建立於 {1}，是否復原到原來的資料夾 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ERR_RECOVER_FILE_M_1 {
            get {
                return ResourceManager.GetString("JE_ERR_RECOVER_FILE_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無效的JSON檔案&quot;{0}.json&quot;，根元素非陣列 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ERR_ROOT_ELEMENT_NOT_ARRAY {
            get {
                return ResourceManager.GetString("JE_ERR_ROOT_ELEMENT_NOT_ARRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   輸出CSV檔案&quot;{0}&quot;失敗，請確認目標資料夾不存在此檔案，並且對資料夾有存取權 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ERR_SAVE_CSV_FAILED {
            get {
                return ResourceManager.GetString("JE_ERR_SAVE_CSV_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   輸出XML檔案&quot;{0}&quot;失敗，請確認目標資料夾不存在此檔案，並且對資料夾有存取權 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ERR_SAVE_XML_FAILED {
            get {
                return ResourceManager.GetString("JE_ERR_SAVE_XML_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   掃描檔案&quot;{0}.csv&quot;時發生錯誤:{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ERR_SCAN_CSV_FILE_FAILED_DEFAULT {
            get {
                return ResourceManager.GetString("JE_ERR_SCAN_CSV_FILE_FAILED_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   掃描檔案失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ERR_SCAN_JSON_FAILED_TITLE {
            get {
                return ResourceManager.GetString("JE_ERR_SCAN_JSON_FAILED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot;轉換至CSV檔案失敗，詳細訊息：&quot;{1}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ERR_TABLE_CONVERT_TO_CSV_FAILED {
            get {
                return ResourceManager.GetString("JE_ERR_TABLE_CONVERT_TO_CSV_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot;轉換至XML檔案失敗，詳細訊息：&quot;{1}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ERR_TABLE_CONVERT_TO_XML_FAILED {
            get {
                return ResourceManager.GetString("JE_ERR_TABLE_CONVERT_TO_XML_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   檔案&quot;{0}.json&quot;資料不合規則：行 {1}，欄位&quot;{2}&quot;， に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ERR_TABLE_INVALID_MESSAGE_PARTIAL {
            get {
                return ResourceManager.GetString("JE_ERR_TABLE_INVALID_MESSAGE_PARTIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}.json&quot;檔案資料與宣告格式不相容，資料載入失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ERR_TABLE_LOAD_JSON_FAILED_DEFAULT {
            get {
                return ResourceManager.GetString("JE_ERR_TABLE_LOAD_JSON_FAILED_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未知的錯誤 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_ERR_UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("JE_ERR_UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取消 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_INPUTBOX_BTN_CANCEL {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_BTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_INPUTBOX_BTN_CONFIRM {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_BTN_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   檔案名稱 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_INPUTBOX_DESCRIPTION {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   欄位名稱 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_INPUTBOX_DESCRIPTION_2 {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_DESCRIPTION_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   檔案庫名稱 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_INPUTBOX_DESCRIPTION_3 {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_DESCRIPTION_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   檔案&quot;{0}:已存在 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_INPUTBOX_FILE_EXISTS {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_FILE_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開新JSON檔案 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_INPUTBOX_TITLE {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新增欄位 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_INPUTBOX_TITLE_2 {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_TITLE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   錯誤的欄位名稱，請用&apos;_&apos;或非特殊文字開頭，之後使用&apos;_&apos;、非特殊文字或是數字，長度不要超過50位 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_INPUTBOX_WRONG_COLUMN_NAME {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_WRONG_COLUMN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不符合規則的檔案庫名稱 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_INPUTBOX_WRONG_DATABASE_NAME {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_WRONG_DATABASE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不符合規則的檔案名稱 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_INPUTBOX_WRONG_FILE_NAME {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_WRONG_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選項 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_LBL_CHOICE_NAME {
            get {
                return ResourceManager.GetString("JE_LBL_CHOICE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   外部索引 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_LIST_FK {
            get {
                return ResourceManager.GetString("JE_LIST_FK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無效 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_LIST_INVALID {
            get {
                return ResourceManager.GetString("JE_LIST_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行資料 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_LIST_ITEMS {
            get {
                return ResourceManager.GetString("JE_LIST_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未讀取 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_LIST_UNLOAD {
            get {
                return ResourceManager.GetString("JE_LIST_UNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   欄位&quot;{0}&quot;已存在 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_ADD_COLUMN_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_ADD_COLUMN_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   欄位&quot;{0}&quot;已移至底端 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_COLUMN_MOVE_DOWN_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_COLUMN_MOVE_DOWN_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動欄位 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_COLUMN_MOVE_TITLE {
            get {
                return ResourceManager.GetString("JE_RUN_COLUMN_MOVE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   欄位&quot;{0}&quot;已移至頂端 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_COLUMN_MOVE_UP_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_COLUMN_MOVE_UP_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot;已新增資料行，第{1}行資料已複製 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_COPY_LINE_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_COPY_LINE_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   檔案內存在{0}筆資料，確定要一起刪除欄位嗎 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_DELETE_COLUMN_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_DELETE_COLUMN_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   欄位&quot;{0}&quot;已刪除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_DELETE_COLUMN_M_2 {
            get {
                return ResourceManager.GetString("JE_RUN_DELETE_COLUMN_M_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確定刪除檔案&quot;{0}.json&quot;？(存檔後檔案將無法復原) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_DELETE_JSON_FILE_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_DELETE_JSON_FILE_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   檔案&quot;{0}.json&quot;已刪除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_DELETE_JSON_FILE_M_5 {
            get {
                return ResourceManager.GetString("JE_RUN_DELETE_JSON_FILE_M_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot;資料行已刪除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_DELETE_LINE_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_DELETE_LINE_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   存在不符合規則的資料，確定輸出？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_EXPORT_INVALID_FILE {
            get {
                return ResourceManager.GetString("JE_RUN_EXPORT_INVALID_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   已使用CSV格式輸出至&quot;{0}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_EXPORT_TO_CSV_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_EXPORT_TO_CSV_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   已使用XML格式輸出至&quot;{0}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_EXPORT_TO_XML_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_EXPORT_TO_XML_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   欄位&quot;{0}&quot;，值&quot;{1}&quot;，搜尋失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_FIND_NO_ITEM_FOUND {
            get {
                return ResourceManager.GetString("JE_RUN_FIND_NO_ITEM_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   尋找資料 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_FIND_TITLE {
            get {
                return ResourceManager.GetString("JE_RUN_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   資料行&quot;{0}&quot;已移至底端 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_LINE_MOVE_DOWN_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_LINE_MOVE_DOWN_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動資料行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_LINE_MOVE_TITLE {
            get {
                return ResourceManager.GetString("JE_RUN_LINE_MOVE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   資料行&quot;{0}&quot;已移至頂端 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_LINE_MOVE_UP_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_LINE_MOVE_UP_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}檔案已讀入 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_LOAD_JSON_FILES_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_LOAD_JSON_FILES_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JSON關聯檔案不存在，掃描JSON資料夾以建立新的關聯檔案 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_LOAD_JSON_FILES_M_2 {
            get {
                return ResourceManager.GetString("JE_RUN_LOAD_JSON_FILES_M_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   目標資料夾&quot;{0}&quot;沒有Json檔案存在 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_LOAD_JSON_FILES_M_3 {
            get {
                return ResourceManager.GetString("JE_RUN_LOAD_JSON_FILES_M_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   檔案&quot;{0}.json&quot;未在JSON關聯檔案中出現，請確認JSON檔案是否正確 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_LOAD_JSON_FILES_M_4 {
            get {
                return ResourceManager.GetString("JE_RUN_LOAD_JSON_FILES_M_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   讀取檔案庫 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_LOAD_JSON_FILES_TITLE {
            get {
                return ResourceManager.GetString("JE_RUN_LOAD_JSON_FILES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   檔案新建失敗:&quot;{0}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_NEW_JSON_FILE_M_2 {
            get {
                return ResourceManager.GetString("JE_RUN_NEW_JSON_FILE_M_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開新檔案 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_NEW_JSON_FILE_TITLE {
            get {
                return ResourceManager.GetString("JE_RUN_NEW_JSON_FILE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   已在&quot;{0}&quot;新建檔案庫 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_NEW_JSON_FILES_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_NEW_JSON_FILES_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   資料夾已有現存 {0} JSON檔案，是否要清空資料夾 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_NEW_JSON_FILES_Q_1 {
            get {
                return ResourceManager.GetString("JE_RUN_NEW_JSON_FILES_Q_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開新檔案庫 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_NEW_JSON_FILES_TITLE {
            get {
                return ResourceManager.GetString("JE_RUN_NEW_JSON_FILES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot;已新增資料 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_NEW_LINE_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_NEW_LINE_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   檔案沒有欄位不能新增資料 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_NEW_LINE_M_2 {
            get {
                return ResourceManager.GetString("JE_RUN_NEW_LINE_M_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   重新產生資料中欄位&quot;{0}&quot;的索引值，確定(覆蓋原值)？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_REGENERATE_KEY_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_REGENERATE_KEY_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   欄位&quot;{0}&quot;索引值已重設 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_REGENERATE_KEY_M_2 {
            get {
                return ResourceManager.GetString("JE_RUN_REGENERATE_KEY_M_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   欄位&quot;{0}&quot;已存在 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_RENAME_COLUMN_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_RENAME_COLUMN_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   欄位已重新命名為&quot;{0}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_RENAME_COLUMN_M_2 {
            get {
                return ResourceManager.GetString("JE_RUN_RENAME_COLUMN_M_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   重新命名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_RENAME_COLUMN_TITLE {
            get {
                return ResourceManager.GetString("JE_RUN_RENAME_COLUMN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   檔案庫已重新命名為&quot;{0}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_RENAME_DATABASE_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_RENAME_DATABASE_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   檔案&quot;{0}.json&quot;已存在 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_RENAME_JSON_FILE_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_RENAME_JSON_FILE_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   檔案已重新命名為&quot;{0}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_RENAME_JSON_FILE_M_2 {
            get {
                return ResourceManager.GetString("JE_RUN_RENAME_JSON_FILE_M_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   這不是一個空的資料夾，將清空所有檔案，你確定嗎? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_SAVE_AS_JSON_FILES_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_SAVE_AS_JSON_FILES_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   檔案庫&quot;{0}&quot;尚未存檔，是否存檔？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_SAVE_FILES_CHECK {
            get {
                return ResourceManager.GetString("JE_RUN_SAVE_FILES_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   存檔取消，檔案&quot;{0}.json&quot;，資料不合規則 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_SAVE_JSON_FILES_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_SAVE_JSON_FILES_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot;所有檔案已存檔 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_SAVE_JSON_FILES_M_2 {
            get {
                return ResourceManager.GetString("JE_RUN_SAVE_JSON_FILES_M_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   目標資料夾&quot;{0}&quot;沒有csv檔案存在 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_SCAN_CSV_FILES_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_SCAN_CSV_FILES_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}檔案掃描完畢 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_SCAN_CSV_FILES_M_2 {
            get {
                return ResourceManager.GetString("JE_RUN_SCAN_CSV_FILES_M_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   資料夾&quot;{0}&quot;已存在JSON關聯檔案，確定繼續掃描目標資料夾？(之後存檔後將覆蓋舊的JSON關聯檔) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_SCAN_JSON_FILES_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_SCAN_JSON_FILES_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}檔案掃描完畢 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_SCAN_JSON_FILES_M_2 {
            get {
                return ResourceManager.GetString("JE_RUN_SCAN_JSON_FILES_M_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   掃描檔案庫 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_SCAN_JSON_FILES_TITLE {
            get {
                return ResourceManager.GetString("JE_RUN_SCAN_JSON_FILES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   檔案內存在{0}筆資料，確定要一起更改嗎(型態不合的資料將設為初始值) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_UPDATE_COLUMN_M_5 {
            get {
                return ResourceManager.GetString("JE_RUN_UPDATE_COLUMN_M_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   欄位&quot;{0}&quot;已更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_UPDATE_COLUMN_M_6 {
            get {
                return ResourceManager.GetString("JE_RUN_UPDATE_COLUMN_M_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新欄位 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_UPDATE_COLUMN_TITLE {
            get {
                return ResourceManager.GetString("JE_RUN_UPDATE_COLUMN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot;資料已更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_RUN_UPDATE_LINE_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_UPDATE_LINE_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   關於 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_ABOUT {
            get {
                return ResourceManager.GetString("JE_TMI_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   增加欄位 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_ADD_COLUMN {
            get {
                return ResourceManager.GetString("JE_TMI_ADD_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   關閉檔案庫 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_CLOSE_ALL_FILES {
            get {
                return ResourceManager.GetString("JE_TMI_CLOSE_ALL_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   關閉 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_CLOSE_JSON_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_CLOSE_JSON_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   關閉檔案 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_CLOSE_TAB {
            get {
                return ResourceManager.GetString("JE_TMI_CLOSE_TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   收縮全部 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_COLLAPSE_ALL {
            get {
                return ResourceManager.GetString("JE_TMI_COLLAPSE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   下移 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_COLUMN_MOVE_DOWN {
            get {
                return ResourceManager.GetString("JE_TMI_COLUMN_MOVE_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上移 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_COLUMN_MOVE_UP {
            get {
                return ResourceManager.GetString("JE_TMI_COLUMN_MOVE_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   顯示欄位 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_COLUMN_SHOW_ON_LIST {
            get {
                return ResourceManager.GetString("JE_TMI_COLUMN_SHOW_ON_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   刪除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_DELETE_COLUMN {
            get {
                return ResourceManager.GetString("JE_TMI_DELETE_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   刪除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_DELETE_JSON_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_DELETE_JSON_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   顯示所有欄位 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_DISPLAY_ALL_COLUMN {
            get {
                return ResourceManager.GetString("JE_TMI_DISPLAY_ALL_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   離開 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_EXIT {
            get {
                return ResourceManager.GetString("JE_TMI_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   展開全部 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_EXPAND_ALL {
            get {
                return ResourceManager.GetString("JE_TMI_EXPAND_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   輸出 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_EXPORT {
            get {
                return ResourceManager.GetString("JE_TMI_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   輸出 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_EXPORT_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_EXPORT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   輸出為CSV檔案 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_EXPORT_TO_CSV {
            get {
                return ResourceManager.GetString("JE_TMI_EXPORT_TO_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   輸出為CSV檔案 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_EXPORT_TO_CSV_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_EXPORT_TO_CSV_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   輸出為XML檔案 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_EXPORT_TO_XML {
            get {
                return ResourceManager.GetString("JE_TMI_EXPORT_TO_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   輸出為XML檔案 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_EXPORT_TO_XML_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_EXPORT_TO_XML_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   檔案 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   說明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_HELP {
            get {
                return ResourceManager.GetString("JE_TMI_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   語言 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_LANGUAGES {
            get {
                return ResourceManager.GetString("JE_TMI_LANGUAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   讀取JSON檔案庫 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_LOAD_JSON_FILES {
            get {
                return ResourceManager.GetString("JE_TMI_LOAD_JSON_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新增JSON檔案 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_NEW_JSON_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_NEW_JSON_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新建JSON檔案庫 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_NEW_JSON_FILES {
            get {
                return ResourceManager.GetString("JE_TMI_NEW_JSON_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   打開資料夾 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_OPEN_FOLDER {
            get {
                return ResourceManager.GetString("JE_TMI_OPEN_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開啟 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_OPEN_JSON_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_OPEN_JSON_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   重新整理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_REFRESH_FILES {
            get {
                return ResourceManager.GetString("JE_TMI_REFRESH_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   重新命名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_RENAME_COLUMN {
            get {
                return ResourceManager.GetString("JE_TMI_RENAME_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   重新命名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_RENAME_DATABASE {
            get {
                return ResourceManager.GetString("JE_TMI_RENAME_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   重新命名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_RENAME_JSON_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_RENAME_JSON_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   另存JSON檔案庫 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_SAVE_AS_JSON_FILES {
            get {
                return ResourceManager.GetString("JE_TMI_SAVE_AS_JSON_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   存取JSON檔案庫 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_SAVE_JSON_FILES {
            get {
                return ResourceManager.GetString("JE_TMI_SAVE_JSON_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   掃描 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_SCAN {
            get {
                return ResourceManager.GetString("JE_TMI_SCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   掃描CSV檔案資料夾 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_SCAN_CSV_FILES {
            get {
                return ResourceManager.GetString("JE_TMI_SCAN_CSV_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   掃描JSON檔案資料夾 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_SCAN_JSON_FILES {
            get {
                return ResourceManager.GetString("JE_TMI_SCAN_JSON_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   用記事本開啟JSON關聯檔 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_VIEW_JFI_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_VIEW_JFI_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   用記事本開啟 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_TMI_VIEW_JSON_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_VIEW_JSON_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   值&quot;{0}&quot;，選項不存在 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_CHOICE_VALUE_NOT_EXIST {
            get {
                return ResourceManager.GetString("JE_VAL_CHOICE_VALUE_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動產生索引欄位適用在不正確的型別上(只有數字、字串或是Guid可以被自動產生) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_COLUMN_AUTO_GENERATE_KEY_WITH_INAPPROPRIATE_TYPE {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_AUTO_GENERATE_KEY_WITH_INAPPROPRIATE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動產生索引欄位附帶限制條件(最小值、最大值、文字長度或正則表達式) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_COLUMN_AUTO_GENERATE_KEY_WITH_RESTRICT {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_AUTO_GENERATE_KEY_WITH_RESTRICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選擇欄位沒有可選值 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_COLUMN_CHOICE_TYPE_CHOICES_NOT_EXISTS {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_CHOICE_TYPE_CHOICES_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   外部索引欄位名遺失 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_COLUMN_FK_COLUMN_MISSING {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_FK_COLUMN_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   外部索引欄位不存在 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_COLUMN_FK_COLUMN_NOT_EXIST {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_FK_COLUMN_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   外部索引欄位型別與此欄位型別不合 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_COLUMN_FK_COLUMN_TYPE_NOT_MATCH {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_FK_COLUMN_TYPE_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   外部索引檔案名遺失 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_COLUMN_FK_TABLE_MISSING {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_FK_TABLE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   外部索引檔案不存在 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_COLUMN_FK_TABLE_NOT_EXIST {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_FK_TABLE_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   欄位名稱不正確 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_COLUMN_ILLEGAL_NAME {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_ILLEGAL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正則表達式格式錯誤 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_COLUMN_ILLEGAL_REGULAR_EXPRESSION {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_ILLEGAL_REGULAR_EXPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key欄位不能為Null值 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_COLUMN_IS_KEY_AND_IS_NULL {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_IS_KEY_AND_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字最大長度錯誤，合法值為0(不限)或正整數 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_COLUMN_MAX_LEGNTH_IS_NEGATIVE {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_MAX_LEGNTH_IS_NEGATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot;不是正確的最大值 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_COLUMN_MAX_VALUE_CAST_FAILED {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_MAX_VALUE_CAST_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot;不是正確的最小值 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_COLUMN_MIN_VALUE_CAST_FAILED {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_MIN_VALUE_CAST_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最小值&quot;{0}&quot;高於最大值&quot;{1}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_COLUMN_MIN_VALUE_GREATER_THAN_MAX_VALUE {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_MIN_VALUE_GREATER_THAN_MAX_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   非數字或日期時間含有最大值 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_COLUMN_NOT_NUMBER_OR_DATETIME_HAVE_MAX_VALUE {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_NOT_NUMBER_OR_DATETIME_HAVE_MAX_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   非數字或日期時間含有最小值 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_COLUMN_NOT_NUMBER_OR_DATETIME_HAVE_MIN_VALUE {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_NOT_NUMBER_OR_DATETIME_HAVE_MIN_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   欄位行數過大或為負值 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_COLUMN_NUMBER_OF_ROWS_IS_NEGATIVE_OR_TOO_BIG {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_NUMBER_OF_ROWS_IS_NEGATIVE_OR_TOO_BIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   數字或日期時間含有正則表達式驗證 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_COLUMN_NUMBER_OR_DATETIME_HAS_REGULAR_EXPRESSION {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_NUMBER_OR_DATETIME_HAS_REGULAR_EXPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   鍵值&quot;{0}&quot;重複 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_DUPLICATE_KEY {
            get {
                return ResourceManager.GetString("JE_VAL_DUPLICATE_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   外部索引值&quot;{0}&quot;不存在 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_FK_VALUE_NOT_FOUND {
            get {
                return ResourceManager.GetString("JE_VAL_FK_VALUE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot;高於最大值&quot;{1}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_GREATER_THEN_MAX_VALUE {
            get {
                return ResourceManager.GetString("JE_VAL_GREATER_THEN_MAX_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot;不符合資料型態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_INVALID_CAST {
            get {
                return ResourceManager.GetString("JE_VAL_INVALID_CAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JSON關聯檔案不合規則：檔案&quot;{0}&quot;，欄位&quot;{1}&quot;， に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_JFI_FILE_INVALID_MESSAGE_PARTIAL {
            get {
                return ResourceManager.GetString("JE_VAL_JFI_FILE_INVALID_MESSAGE_PARTIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot;低於最小值&quot;{1}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_LESS_THEN_MIN_VALUE {
            get {
                return ResourceManager.GetString("JE_VAL_LESS_THEN_MIN_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不可以為Null值 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_NOT_NULLABLE {
            get {
                return ResourceManager.GetString("JE_VAL_NOT_NULLABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot;規則檢查失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_REGEX_IS_NOT_MATCH {
            get {
                return ResourceManager.GetString("JE_VAL_REGEX_IS_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字超過最大長度{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_TEXT_MAXIMUM_LENGTH_OVER {
            get {
                return ResourceManager.GetString("JE_VAL_TEXT_MAXIMUM_LENGTH_OVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   值&quot;{0}&quot;已存在 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JE_VAL_VALUE_IS_NOT_UNIQUE {
            get {
                return ResourceManager.GetString("JE_VAL_VALUE_IS_NOT_UNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JSON 資料檔案編輯器 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JSON_FILE_EDITOR_TITLE {
            get {
                return ResourceManager.GetString("JSON_FILE_EDITOR_TITLE", resourceCulture);
            }
        }
    }
}
