//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonEditorV2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JsonEditorV2.Resources.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON 資料檔案編輯器.
        /// </summary>
        public static string JE_ABOUT_MESSAGE {
            get {
                return ResourceManager.GetString("JE_ABOUT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作者：日瀨健人.
        /// </summary>
        public static string JE_ABOUT_MESSAGE_2 {
            get {
                return ResourceManager.GetString("JE_ABOUT_MESSAGE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關於.
        /// </summary>
        public static string JE_ABOUT_TITLE {
            get {
                return ResourceManager.GetString("JE_ABOUT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空.
        /// </summary>
        public static string JE_BTN_CLEAR_COLUMN {
            get {
                return ResourceManager.GetString("JE_BTN_CLEAR_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空.
        /// </summary>
        public static string JE_BTN_CLEAR_MAIN {
            get {
                return ResourceManager.GetString("JE_BTN_CLEAR_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除資料.
        /// </summary>
        public static string JE_BTN_DELETE_LINE {
            get {
                return ResourceManager.GetString("JE_BTN_DELETE_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新ID.
        /// </summary>
        public static string JE_BTN_NEW_GUID {
            get {
                return ResourceManager.GetString("JE_BTN_NEW_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增資料.
        /// </summary>
        public static string JE_BTN_NEW_LINE {
            get {
                return ResourceManager.GetString("JE_BTN_NEW_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        public static string JE_BTN_UPDATE_COLUMN {
            get {
                return ResourceManager.GetString("JE_BTN_UPDATE_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        public static string JE_BTN_UPDATE_MAIN {
            get {
                return ResourceManager.GetString("JE_BTN_UPDATE_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增.
        /// </summary>
        public static string JE_CHOICES_ADD_ITEM {
            get {
                return ResourceManager.GetString("JE_CHOICES_ADD_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認.
        /// </summary>
        public static string JE_CHOICES_CONFIRM {
            get {
                return ResourceManager.GetString("JE_CHOICES_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除.
        /// </summary>
        public static string JE_CHOICES_DELETE_ITEM {
            get {
                return ResourceManager.GetString("JE_CHOICES_DELETE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 快速檢查.
        /// </summary>
        public static string JE_CKB_QUICK_CEHCK {
            get {
                return ResourceManager.GetString("JE_CKB_QUICK_CEHCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動產生索引值.
        /// </summary>
        public static string JE_COLUMN_AUTO_GENERATE_KEY {
            get {
                return ResourceManager.GetString("JE_COLUMN_AUTO_GENERATE_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欄位可選值.
        /// </summary>
        public static string JE_COLUMN_CHOICES {
            get {
                return ResourceManager.GetString("JE_COLUMN_CHOICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欄位描述.
        /// </summary>
        public static string JE_COLUMN_DESCRIPTION {
            get {
                return ResourceManager.GetString("JE_COLUMN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顯示在清單上.
        /// </summary>
        public static string JE_COLUMN_DISPLAY {
            get {
                return ResourceManager.GetString("JE_COLUMN_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外部索引欄位.
        /// </summary>
        public static string JE_COLUMN_FK_COLUMN {
            get {
                return ResourceManager.GetString("JE_COLUMN_FK_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外部索引檔案.
        /// </summary>
        public static string JE_COLUMN_FK_TABLE {
            get {
                return ResourceManager.GetString("JE_COLUMN_FK_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是索引.
        /// </summary>
        public static string JE_COLUMN_IS_KEY {
            get {
                return ResourceManager.GetString("JE_COLUMN_IS_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可以為Null值.
        /// </summary>
        public static string JE_COLUMN_IS_NULLABLE {
            get {
                return ResourceManager.GetString("JE_COLUMN_IS_NULLABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 唯一值.
        /// </summary>
        public static string JE_COLUMN_IS_UNIQUE {
            get {
                return ResourceManager.GetString("JE_COLUMN_IS_UNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字最大長度.
        /// </summary>
        public static string JE_COLUMN_MAX_LENGTH {
            get {
                return ResourceManager.GetString("JE_COLUMN_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大值.
        /// </summary>
        public static string JE_COLUMN_MAX_VALUE {
            get {
                return ResourceManager.GetString("JE_COLUMN_MAX_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最小值.
        /// </summary>
        public static string JE_COLUMN_MIN_VALUE {
            get {
                return ResourceManager.GetString("JE_COLUMN_MIN_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欄位名稱.
        /// </summary>
        public static string JE_COLUMN_NAME {
            get {
                return ResourceManager.GetString("JE_COLUMN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欄位行數.
        /// </summary>
        public static string JE_COLUMN_NUM_OF_ROWS {
            get {
                return ResourceManager.GetString("JE_COLUMN_NUM_OF_ROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正則表達式.
        /// </summary>
        public static string JE_COLUMN_REGEX {
            get {
                return ResourceManager.GetString("JE_COLUMN_REGEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欄位型別.
        /// </summary>
        public static string JE_COLUMN_TYPE {
            get {
                return ResourceManager.GetString("JE_COLUMN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無效的JSON檔案&quot;{0}.json&quot;，索引：{1}，欄位數量過多或過少.
        /// </summary>
        public static string JE_ERR_CHILD_COLUMN_COUNT_VARY {
            get {
                return ResourceManager.GetString("JE_ERR_CHILD_COLUMN_COUNT_VARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無效的JSON檔案&quot;{0}.json&quot;，索引：{1}，欄位名稱&quot;{2}&quot;，不正確.
        /// </summary>
        public static string JE_ERR_CHILD_COLUMN_NAME_VARY {
            get {
                return ResourceManager.GetString("JE_ERR_CHILD_COLUMN_NAME_VARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無效的JSON檔案&quot;{0}.json&quot;，索引：{1}，欄位&quot;{2}&quot;順序不正確.
        /// </summary>
        public static string JE_ERR_CHILD_COLUMN_ORDER_VARY {
            get {
                return ResourceManager.GetString("JE_ERR_CHILD_COLUMN_ORDER_VARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無效的JSON檔案&quot;{0}.json&quot;，索引：{1}，欄位&quot;{2}&quot;型別種類太多.
        /// </summary>
        public static string JE_ERR_CHILD_COLUMN_TYPE_VARY {
            get {
                return ResourceManager.GetString("JE_ERR_CHILD_COLUMN_TYPE_VARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無效的JSON檔案&quot;{0}.json&quot;，索引：{1}，子元素非物件.
        /// </summary>
        public static string JE_ERR_CHILD_ELEMENT_NOT_OBJECT {
            get {
                return ResourceManager.GetString("JE_ERR_CHILD_ELEMENT_NOT_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 錯誤發生：&quot;{0}&quot;.
        /// </summary>
        public static string JE_ERR_DEFAULT_MESSAGE {
            get {
                return ResourceManager.GetString("JE_ERR_DEFAULT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 錯誤.
        /// </summary>
        public static string JE_ERR_DEFAULT_TITLE {
            get {
                return ResourceManager.GetString("JE_ERR_DEFAULT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON關聯檔案格式不正確：{0}.
        /// </summary>
        public static string JE_ERR_JSONCONVERT_DESERIALIZE_JFI_FAILED_DEFAULT {
            get {
                return ResourceManager.GetString("JE_ERR_JSONCONVERT_DESERIALIZE_JFI_FAILED_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案&quot;{0}.json&quot;格式不正確：{1}.
        /// </summary>
        public static string JE_ERR_JSONCONVERT_DESERIALIZE_OBJECT_FAILED_DEFAULT {
            get {
                return ResourceManager.GetString("JE_ERR_JSONCONVERT_DESERIALIZE_OBJECT_FAILED_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 讀取JSON關聯檔案&quot;{0}&quot;失敗，請確認檔案是否存在或損毀.
        /// </summary>
        public static string JE_ERR_LOAD_JFI_FILE_FAILED_DEFAULT {
            get {
                return ResourceManager.GetString("JE_ERR_LOAD_JFI_FILE_FAILED_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 讀取檔案失敗.
        /// </summary>
        public static string JE_ERR_LOAD_JSON_FAILED_TITLE {
            get {
                return ResourceManager.GetString("JE_ERR_LOAD_JSON_FAILED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 讀取檔案&quot;{0}&quot;時發生錯誤，請確認檔案是否存在或損毀.
        /// </summary>
        public static string JE_ERR_LOAD_JSON_FILE_FAILED_DEFAULT {
            get {
                return ResourceManager.GetString("JE_ERR_LOAD_JSON_FILE_FAILED_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 發現需要復原的檔案&quot;{0}&quot;建立於 {1}，是否復原到原來的資料夾.
        /// </summary>
        public static string JE_ERR_RECOVER_FILE_M_1 {
            get {
                return ResourceManager.GetString("JE_ERR_RECOVER_FILE_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無效的JSON檔案&quot;{0}.json&quot;，根元素非陣列.
        /// </summary>
        public static string JE_ERR_ROOT_ELEMENT_NOT_ARRAY {
            get {
                return ResourceManager.GetString("JE_ERR_ROOT_ELEMENT_NOT_ARRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 掃描檔案失敗.
        /// </summary>
        public static string JE_ERR_SCAN_JSON_FAILED_TITLE {
            get {
                return ResourceManager.GetString("JE_ERR_SCAN_JSON_FAILED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案&quot;{0}.json&quot;資料不合規則：行 {1}，欄位&quot;{2}&quot;，.
        /// </summary>
        public static string JE_ERR_TABLE_INVALID_MESSAGE_PARTIAL {
            get {
                return ResourceManager.GetString("JE_ERR_TABLE_INVALID_MESSAGE_PARTIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}.json&quot;檔案資料與宣告格式不相容，資料載入失敗.
        /// </summary>
        public static string JE_ERR_TABLE_LOAD_JSON_FAILED_DEFAULT {
            get {
                return ResourceManager.GetString("JE_ERR_TABLE_LOAD_JSON_FAILED_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知的錯誤.
        /// </summary>
        public static string JE_ERR_UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("JE_ERR_UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string JE_INPUTBOX_BTN_CANCEL {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_BTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確定.
        /// </summary>
        public static string JE_INPUTBOX_BTN_CONFIRM {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_BTN_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案名稱.
        /// </summary>
        public static string JE_INPUTBOX_DESCRIPTION {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欄位名稱.
        /// </summary>
        public static string JE_INPUTBOX_DESCRIPTION_2 {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_DESCRIPTION_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案庫名稱.
        /// </summary>
        public static string JE_INPUTBOX_DESCRIPTION_3 {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_DESCRIPTION_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案&quot;{0}:已存在.
        /// </summary>
        public static string JE_INPUTBOX_FILE_EXISTS {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_FILE_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開新JSON檔案.
        /// </summary>
        public static string JE_INPUTBOX_TITLE {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增欄位.
        /// </summary>
        public static string JE_INPUTBOX_TITLE_2 {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_TITLE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 錯誤的欄位名稱，請用&apos;_&apos;或非特殊文字開頭，之後使用&apos;_&apos;、非特殊文字或是數字，長度不要超過50位.
        /// </summary>
        public static string JE_INPUTBOX_WRONG_COLUMN_NAME {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_WRONG_COLUMN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不符合規則的檔案庫名稱.
        /// </summary>
        public static string JE_INPUTBOX_WRONG_DATABASE_NAME {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_WRONG_DATABASE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不符合規則的檔案名稱.
        /// </summary>
        public static string JE_INPUTBOX_WRONG_FILE_NAME {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_WRONG_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選項.
        /// </summary>
        public static string JE_LBL_CHOICE_NAME {
            get {
                return ResourceManager.GetString("JE_LBL_CHOICE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欄位&quot;{0}&quot;已存在.
        /// </summary>
        public static string JE_RUN_ADD_COLUMN_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_ADD_COLUMN_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欄位&quot;{0}&quot;已移至底端.
        /// </summary>
        public static string JE_RUN_COLUMN_MOVE_DOWN_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_COLUMN_MOVE_DOWN_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移動欄位.
        /// </summary>
        public static string JE_RUN_COLUMN_MOVE_TITLE {
            get {
                return ResourceManager.GetString("JE_RUN_COLUMN_MOVE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欄位&quot;{0}&quot;已移至頂端.
        /// </summary>
        public static string JE_RUN_COLUMN_MOVE_UP_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_COLUMN_MOVE_UP_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案內存在{0}筆資料，確定要一起刪除欄位嗎.
        /// </summary>
        public static string JE_RUN_DELETE_COLUMN_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_DELETE_COLUMN_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欄位&quot;{0}&quot;已刪除.
        /// </summary>
        public static string JE_RUN_DELETE_COLUMN_M_2 {
            get {
                return ResourceManager.GetString("JE_RUN_DELETE_COLUMN_M_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確定刪除檔案&quot;{0}.json&quot;？(存檔後檔案將無法復原).
        /// </summary>
        public static string JE_RUN_DELETE_JSON_FILE_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_DELETE_JSON_FILE_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案&quot;{0}.json&quot;已刪除.
        /// </summary>
        public static string JE_RUN_DELETE_JSON_FILE_M_5 {
            get {
                return ResourceManager.GetString("JE_RUN_DELETE_JSON_FILE_M_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;資料已刪除.
        /// </summary>
        public static string JE_RUN_DELETE_LINE_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_DELETE_LINE_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欄位&quot;{0}&quot;，值&quot;{1}&quot;，搜尋失敗.
        /// </summary>
        public static string JE_RUN_FIND_NO_ITEM_FOUND {
            get {
                return ResourceManager.GetString("JE_RUN_FIND_NO_ITEM_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尋找資料.
        /// </summary>
        public static string JE_RUN_FIND_TITLE {
            get {
                return ResourceManager.GetString("JE_RUN_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資料行&quot;{0}&quot;已移至底端.
        /// </summary>
        public static string JE_RUN_LINE_MOVE_DOWN_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_LINE_MOVE_DOWN_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移動資料行.
        /// </summary>
        public static string JE_RUN_LINE_MOVE_TITLE {
            get {
                return ResourceManager.GetString("JE_RUN_LINE_MOVE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資料行&quot;{0}&quot;已移至頂端.
        /// </summary>
        public static string JE_RUN_LINE_MOVE_UP_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_LINE_MOVE_UP_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}檔案已讀入.
        /// </summary>
        public static string JE_RUN_LOAD_JSON_FILES_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_LOAD_JSON_FILES_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON關聯檔案不存在，掃描JSON資料夾以建立新的關聯檔案.
        /// </summary>
        public static string JE_RUN_LOAD_JSON_FILES_M_2 {
            get {
                return ResourceManager.GetString("JE_RUN_LOAD_JSON_FILES_M_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目標資料夾&quot;{0}&quot;沒有Json檔案存在.
        /// </summary>
        public static string JE_RUN_LOAD_JSON_FILES_M_3 {
            get {
                return ResourceManager.GetString("JE_RUN_LOAD_JSON_FILES_M_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案&quot;{0}.json&quot;未在JSON關聯檔案中出現，請確認JSON檔案是否正確.
        /// </summary>
        public static string JE_RUN_LOAD_JSON_FILES_M_4 {
            get {
                return ResourceManager.GetString("JE_RUN_LOAD_JSON_FILES_M_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 讀取檔案庫.
        /// </summary>
        public static string JE_RUN_LOAD_JSON_FILES_TITLE {
            get {
                return ResourceManager.GetString("JE_RUN_LOAD_JSON_FILES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案新建失敗:&quot;{0}&quot;.
        /// </summary>
        public static string JE_RUN_NEW_JSON_FILE_M_2 {
            get {
                return ResourceManager.GetString("JE_RUN_NEW_JSON_FILE_M_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開新檔案.
        /// </summary>
        public static string JE_RUN_NEW_JSON_FILE_TITLE {
            get {
                return ResourceManager.GetString("JE_RUN_NEW_JSON_FILE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已在&quot;{0}&quot;新建檔案庫.
        /// </summary>
        public static string JE_RUN_NEW_JSON_FILES_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_NEW_JSON_FILES_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資料夾已有現存 {0} JSON檔案，是否要清空資料夾.
        /// </summary>
        public static string JE_RUN_NEW_JSON_FILES_Q_1 {
            get {
                return ResourceManager.GetString("JE_RUN_NEW_JSON_FILES_Q_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開新檔案庫.
        /// </summary>
        public static string JE_RUN_NEW_JSON_FILES_TITLE {
            get {
                return ResourceManager.GetString("JE_RUN_NEW_JSON_FILES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;已新增資料.
        /// </summary>
        public static string JE_RUN_NEW_LINE_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_NEW_LINE_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案沒有欄位不能新增資料.
        /// </summary>
        public static string JE_RUN_NEW_LINE_M_2 {
            get {
                return ResourceManager.GetString("JE_RUN_NEW_LINE_M_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欄位&quot;{0}&quot;已存在.
        /// </summary>
        public static string JE_RUN_RENAME_COLUMN_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_RENAME_COLUMN_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欄位已重新命名為&quot;{0}&quot;.
        /// </summary>
        public static string JE_RUN_RENAME_COLUMN_M_2 {
            get {
                return ResourceManager.GetString("JE_RUN_RENAME_COLUMN_M_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新命名.
        /// </summary>
        public static string JE_RUN_RENAME_COLUMN_TITLE {
            get {
                return ResourceManager.GetString("JE_RUN_RENAME_COLUMN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案庫已重新命名為&quot;{0}&quot;.
        /// </summary>
        public static string JE_RUN_RENAME_DATABASE_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_RENAME_DATABASE_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案&quot;{0}.json&quot;已存在.
        /// </summary>
        public static string JE_RUN_RENAME_JSON_FILE_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_RENAME_JSON_FILE_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案已重新命名為&quot;{0}&quot;.
        /// </summary>
        public static string JE_RUN_RENAME_JSON_FILE_M_2 {
            get {
                return ResourceManager.GetString("JE_RUN_RENAME_JSON_FILE_M_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 這不是一個空的資料夾，將清空所有檔案，你確定嗎?.
        /// </summary>
        public static string JE_RUN_SAVE_AS_JSON_FILES_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_SAVE_AS_JSON_FILES_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案庫&quot;{0}&quot;尚未存檔，是否存檔？.
        /// </summary>
        public static string JE_RUN_SAVE_FILES_CHECK {
            get {
                return ResourceManager.GetString("JE_RUN_SAVE_FILES_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存檔取消，檔案&quot;{0}.json&quot;，資料不合規則.
        /// </summary>
        public static string JE_RUN_SAVE_JSON_FILES_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_SAVE_JSON_FILES_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;所有檔案已存檔.
        /// </summary>
        public static string JE_RUN_SAVE_JSON_FILES_M_2 {
            get {
                return ResourceManager.GetString("JE_RUN_SAVE_JSON_FILES_M_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資料夾&quot;{0}&quot;已存在JSON關聯檔案，確定繼續掃描目標資料夾？(之後存檔後將覆蓋舊的JSON關聯檔).
        /// </summary>
        public static string JE_RUN_SCAN_JSON_FILES_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_SCAN_JSON_FILES_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}檔案掃描完畢.
        /// </summary>
        public static string JE_RUN_SCAN_JSON_FILES_M_2 {
            get {
                return ResourceManager.GetString("JE_RUN_SCAN_JSON_FILES_M_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 掃描檔案庫.
        /// </summary>
        public static string JE_RUN_SCAN_JSON_FILES_TITLE {
            get {
                return ResourceManager.GetString("JE_RUN_SCAN_JSON_FILES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案內存在{0}筆資料，確定要一起更改嗎(型態不合的資料將設為初始值).
        /// </summary>
        public static string JE_RUN_UPDATE_COLUMN_M_5 {
            get {
                return ResourceManager.GetString("JE_RUN_UPDATE_COLUMN_M_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欄位&quot;{0}&quot;已更新.
        /// </summary>
        public static string JE_RUN_UPDATE_COLUMN_M_6 {
            get {
                return ResourceManager.GetString("JE_RUN_UPDATE_COLUMN_M_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新欄位.
        /// </summary>
        public static string JE_RUN_UPDATE_COLUMN_TITLE {
            get {
                return ResourceManager.GetString("JE_RUN_UPDATE_COLUMN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;資料已更新.
        /// </summary>
        public static string JE_RUN_UPDATE_LINE_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_UPDATE_LINE_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關於.
        /// </summary>
        public static string JE_TMI_ABOUT {
            get {
                return ResourceManager.GetString("JE_TMI_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 增加欄位.
        /// </summary>
        public static string JE_TMI_ADD_COLUMN {
            get {
                return ResourceManager.GetString("JE_TMI_ADD_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關閉檔案庫.
        /// </summary>
        public static string JE_TMI_CLOSE_ALL_FILES {
            get {
                return ResourceManager.GetString("JE_TMI_CLOSE_ALL_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關閉.
        /// </summary>
        public static string JE_TMI_CLOSE_JSON_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_CLOSE_JSON_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關閉檔案.
        /// </summary>
        public static string JE_TMI_CLOSE_TAB {
            get {
                return ResourceManager.GetString("JE_TMI_CLOSE_TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收縮全部.
        /// </summary>
        public static string JE_TMI_COLLAPSE_ALL {
            get {
                return ResourceManager.GetString("JE_TMI_COLLAPSE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下移.
        /// </summary>
        public static string JE_TMI_COLUMN_MOVE_DOWN {
            get {
                return ResourceManager.GetString("JE_TMI_COLUMN_MOVE_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上移.
        /// </summary>
        public static string JE_TMI_COLUMN_MOVE_UP {
            get {
                return ResourceManager.GetString("JE_TMI_COLUMN_MOVE_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顯示欄位.
        /// </summary>
        public static string JE_TMI_COLUMN_SHOW_ON_LIST {
            get {
                return ResourceManager.GetString("JE_TMI_COLUMN_SHOW_ON_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除.
        /// </summary>
        public static string JE_TMI_DELETE_COLUMN {
            get {
                return ResourceManager.GetString("JE_TMI_DELETE_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除.
        /// </summary>
        public static string JE_TMI_DELETE_JSON_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_DELETE_JSON_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 離開.
        /// </summary>
        public static string JE_TMI_EXIT {
            get {
                return ResourceManager.GetString("JE_TMI_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 展開全部.
        /// </summary>
        public static string JE_TMI_EXPAND_ALL {
            get {
                return ResourceManager.GetString("JE_TMI_EXPAND_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案.
        /// </summary>
        public static string JE_TMI_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 語言.
        /// </summary>
        public static string JE_TMI_LANGUAGES {
            get {
                return ResourceManager.GetString("JE_TMI_LANGUAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 讀取JSON檔案庫.
        /// </summary>
        public static string JE_TMI_LOAD_JSON_FILES {
            get {
                return ResourceManager.GetString("JE_TMI_LOAD_JSON_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增JSON檔案.
        /// </summary>
        public static string JE_TMI_NEW_JSON_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_NEW_JSON_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建JSON檔案庫.
        /// </summary>
        public static string JE_TMI_NEW_JSON_FILES {
            get {
                return ResourceManager.GetString("JE_TMI_NEW_JSON_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打開資料夾.
        /// </summary>
        public static string JE_TMI_OPEN_FOLDER {
            get {
                return ResourceManager.GetString("JE_TMI_OPEN_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開啟.
        /// </summary>
        public static string JE_TMI_OPEN_JSON_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_OPEN_JSON_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新整理.
        /// </summary>
        public static string JE_TMI_REFRESH_FILES {
            get {
                return ResourceManager.GetString("JE_TMI_REFRESH_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新命名.
        /// </summary>
        public static string JE_TMI_RENAME_COLUMN {
            get {
                return ResourceManager.GetString("JE_TMI_RENAME_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新命名.
        /// </summary>
        public static string JE_TMI_RENAME_DATABASE {
            get {
                return ResourceManager.GetString("JE_TMI_RENAME_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新命名.
        /// </summary>
        public static string JE_TMI_RENAME_JSON_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_RENAME_JSON_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 另存JSON檔案庫.
        /// </summary>
        public static string JE_TMI_SAVE_AS_JSON_FILES {
            get {
                return ResourceManager.GetString("JE_TMI_SAVE_AS_JSON_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存取JSON檔案庫.
        /// </summary>
        public static string JE_TMI_SAVE_JSON_FILES {
            get {
                return ResourceManager.GetString("JE_TMI_SAVE_JSON_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 掃描JSON檔案庫.
        /// </summary>
        public static string JE_TMI_SCAN_JSON_FILES {
            get {
                return ResourceManager.GetString("JE_TMI_SCAN_JSON_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用記事本開啟JSON關聯檔.
        /// </summary>
        public static string JE_TMI_VIEW_JFI_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_VIEW_JFI_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用記事本開啟.
        /// </summary>
        public static string JE_TMI_VIEW_JSON_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_VIEW_JSON_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動產生索引欄位適用在不正確的型別上(只有數字、字串或是Guid可以被自動產生).
        /// </summary>
        public static string JE_VAL_COLUMN_AUTO_GENERATE_KEY_WITH_INAPPROPRIATE_TYPE {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_AUTO_GENERATE_KEY_WITH_INAPPROPRIATE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動產生索引欄位附帶限制條件(最小值、最大值、文字長度或正則表達式).
        /// </summary>
        public static string JE_VAL_COLUMN_AUTO_GENERATE_KEY_WITH_RESTRICT {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_AUTO_GENERATE_KEY_WITH_RESTRICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外部索引欄位名遺失.
        /// </summary>
        public static string JE_VAL_COLUMN_FK_COLUMN_MISSING {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_FK_COLUMN_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外部索引欄位不存在.
        /// </summary>
        public static string JE_VAL_COLUMN_FK_COLUMN_NOT_EXIST {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_FK_COLUMN_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外部索引欄位型別與此欄位型別不合.
        /// </summary>
        public static string JE_VAL_COLUMN_FK_COLUMN_TYPE_NOT_MATCH {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_FK_COLUMN_TYPE_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外部索引檔案名遺失.
        /// </summary>
        public static string JE_VAL_COLUMN_FK_TABLE_MISSING {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_FK_TABLE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外部索引檔案不存在.
        /// </summary>
        public static string JE_VAL_COLUMN_FK_TABLE_NOT_EXIST {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_FK_TABLE_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欄位名稱不正確.
        /// </summary>
        public static string JE_VAL_COLUMN_ILLEGAL_NAME {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_ILLEGAL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正則表達式格式錯誤.
        /// </summary>
        public static string JE_VAL_COLUMN_ILLEGAL_REGULAR_EXPRESSION {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_ILLEGAL_REGULAR_EXPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key欄位不能為Null值.
        /// </summary>
        public static string JE_VAL_COLUMN_IS_KEY_AND_IS_NULL {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_IS_KEY_AND_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字最大長度錯誤，合法值為0(不限)或正整數.
        /// </summary>
        public static string JE_VAL_COLUMN_MAX_LEGNTH_IS_NEGATIVE {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_MAX_LEGNTH_IS_NEGATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;不是正確的最大值.
        /// </summary>
        public static string JE_VAL_COLUMN_MAX_VALUE_CAST_FAILED {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_MAX_VALUE_CAST_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;不是正確的最小值.
        /// </summary>
        public static string JE_VAL_COLUMN_MIN_VALUE_CAST_FAILED {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_MIN_VALUE_CAST_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最小值&quot;{0}&quot;高於最大值&quot;{1}&quot;.
        /// </summary>
        public static string JE_VAL_COLUMN_MIN_VALUE_GREATER_THAN_MAX_VALUE {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_MIN_VALUE_GREATER_THAN_MAX_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非數字或日期時間含有最大值.
        /// </summary>
        public static string JE_VAL_COLUMN_NOT_NUMBER_OR_DATETIME_HAVE_MAX_VALUE {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_NOT_NUMBER_OR_DATETIME_HAVE_MAX_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非數字或日期時間含有最小值.
        /// </summary>
        public static string JE_VAL_COLUMN_NOT_NUMBER_OR_DATETIME_HAVE_MIN_VALUE {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_NOT_NUMBER_OR_DATETIME_HAVE_MIN_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欄位行數過大或為負值.
        /// </summary>
        public static string JE_VAL_COLUMN_NUMBER_OF_ROWS_IS_NEGATIVE_OR_TOO_BIG {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_NUMBER_OF_ROWS_IS_NEGATIVE_OR_TOO_BIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 數字或日期時間含有正則表達式驗證.
        /// </summary>
        public static string JE_VAL_COLUMN_NUMBER_OR_DATETIME_HAS_REGULAR_EXPRESSION {
            get {
                return ResourceManager.GetString("JE_VAL_COLUMN_NUMBER_OR_DATETIME_HAS_REGULAR_EXPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 鍵值&quot;{0}&quot;重複.
        /// </summary>
        public static string JE_VAL_DUPLICATE_KEY {
            get {
                return ResourceManager.GetString("JE_VAL_DUPLICATE_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外部索引值&quot;{0}&quot;不存在.
        /// </summary>
        public static string JE_VAL_FK_VALUE_NOT_FOUND {
            get {
                return ResourceManager.GetString("JE_VAL_FK_VALUE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;高於最大值&quot;{1}&quot;.
        /// </summary>
        public static string JE_VAL_GREATER_THEN_MAX_VALUE {
            get {
                return ResourceManager.GetString("JE_VAL_GREATER_THEN_MAX_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;不符合資料型態.
        /// </summary>
        public static string JE_VAL_INVALID_CAST {
            get {
                return ResourceManager.GetString("JE_VAL_INVALID_CAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON關聯檔案不合規則：檔案&quot;{0}&quot;，欄位&quot;{1}&quot;，.
        /// </summary>
        public static string JE_VAL_JFI_FILE_INVALID_MESSAGE_PARTIAL {
            get {
                return ResourceManager.GetString("JE_VAL_JFI_FILE_INVALID_MESSAGE_PARTIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;低於最小值&quot;{1}&quot;.
        /// </summary>
        public static string JE_VAL_LESS_THEN_MIN_VALUE {
            get {
                return ResourceManager.GetString("JE_VAL_LESS_THEN_MIN_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不可以為Null值.
        /// </summary>
        public static string JE_VAL_NOT_NULLABLE {
            get {
                return ResourceManager.GetString("JE_VAL_NOT_NULLABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;規則檢查失敗.
        /// </summary>
        public static string JE_VAL_REGEX_IS_NOT_MATCH {
            get {
                return ResourceManager.GetString("JE_VAL_REGEX_IS_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字超過最大長度{0}.
        /// </summary>
        public static string JE_VAL_TEXT_MAXIMUM_LENGTH_OVER {
            get {
                return ResourceManager.GetString("JE_VAL_TEXT_MAXIMUM_LENGTH_OVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 值&quot;{0}&quot;已存在.
        /// </summary>
        public static string JE_VAL_VALUE_IS_NOT_UNIQUE {
            get {
                return ResourceManager.GetString("JE_VAL_VALUE_IS_NOT_UNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON 資料檔案編輯器.
        /// </summary>
        public static string JSON_FILE_EDITOR_TITLE {
            get {
                return ResourceManager.GetString("JSON_FILE_EDITOR_TITLE", resourceCulture);
            }
        }
    }
}
