//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonEditorV2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JsonEditorV2.Resources.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON 資料檔案編輯器 0.1.
        /// </summary>
        public static string JE_ABOUT_MESSAGE {
            get {
                return ResourceManager.GetString("JE_ABOUT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by KentKaze.
        /// </summary>
        public static string JE_ABOUT_MESSAGE_2 {
            get {
                return ResourceManager.GetString("JE_ABOUT_MESSAGE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關於.
        /// </summary>
        public static string JE_ABOUT_TITLE {
            get {
                return ResourceManager.GetString("JE_ABOUT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空.
        /// </summary>
        public static string JE_BTN_CLEAR_COLUMN {
            get {
                return ResourceManager.GetString("JE_BTN_CLEAR_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空.
        /// </summary>
        public static string JE_BTN_CLEAR_MAIN {
            get {
                return ResourceManager.GetString("JE_BTN_CLEAR_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        public static string JE_BTN_UPDATE_COLUMN {
            get {
                return ResourceManager.GetString("JE_BTN_UPDATE_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        public static string JE_BTN_UPDATE_MAIN {
            get {
                return ResourceManager.GetString("JE_BTN_UPDATE_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顯示在清單上.
        /// </summary>
        public static string JE_COLUMN_DISPLAY {
            get {
                return ResourceManager.GetString("JE_COLUMN_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外部索引欄位.
        /// </summary>
        public static string JE_COLUMN_FK_COLUMN {
            get {
                return ResourceManager.GetString("JE_COLUMN_FK_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外部索引檔案.
        /// </summary>
        public static string JE_COLUMN_FK_TABLE {
            get {
                return ResourceManager.GetString("JE_COLUMN_FK_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是索引.
        /// </summary>
        public static string JE_COLUMN_IS_KEY {
            get {
                return ResourceManager.GetString("JE_COLUMN_IS_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欄位名稱.
        /// </summary>
        public static string JE_COLUMN_NAME {
            get {
                return ResourceManager.GetString("JE_COLUMN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欄位行數.
        /// </summary>
        public static string JE_COLUMN_NUM_OF_ROWS {
            get {
                return ResourceManager.GetString("JE_COLUMN_NUM_OF_ROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欄位型別.
        /// </summary>
        public static string JE_COLUMN_TYPE {
            get {
                return ResourceManager.GetString("JE_COLUMN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 發生了錯誤，錯誤訊息：&quot;{0}&quot;.
        /// </summary>
        public static string JE_ERROR_DEFAULT_MESSAGE {
            get {
                return ResourceManager.GetString("JE_ERROR_DEFAULT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 錯誤.
        /// </summary>
        public static string JE_ERROR_DEFAULT_TITLE {
            get {
                return ResourceManager.GetString("JE_ERROR_DEFAULT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string JE_INPUTBOX_BTN_CANCEL {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_BTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確定.
        /// </summary>
        public static string JE_INPUTBOX_BTN_CONFIRM {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_BTN_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案名稱.
        /// </summary>
        public static string JE_INPUTBOX_DESCRIPTION {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欄位名稱.
        /// </summary>
        public static string JE_INPUTBOX_DESCRIPTION_2 {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_DESCRIPTION_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案&quot;{0}:已存在.
        /// </summary>
        public static string JE_INPUTBOX_FILE_EXISTS {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_FILE_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開新JSON檔案.
        /// </summary>
        public static string JE_INPUTBOX_TITLE {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增欄位.
        /// </summary>
        public static string JE_INPUTBOX_TITLE_2 {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_TITLE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 錯誤的欄位名稱，請用&apos;_&apos;或英文字母開頭，之後使用&apos;_&apos;、英文字母或是數字，長度不要超過50位.
        /// </summary>
        public static string JE_INPUTBOX_WRONG_COLUMN_NAME {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_WRONG_COLUMN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不符合規則的檔案名稱.
        /// </summary>
        public static string JE_INPUTBOX_WRONG_FILE_NAME {
            get {
                return ResourceManager.GetString("JE_INPUTBOX_WRONG_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}檔案已讀入.
        /// </summary>
        public static string JE_RUN_LOAD_JSON_FILES_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_LOAD_JSON_FILES_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JFilesInfo連結失敗，忽略後繼續編輯:&quot;{0}&quot;.
        /// </summary>
        public static string JE_RUN_LOAD_JSON_FILES_M_2 {
            get {
                return ResourceManager.GetString("JE_RUN_LOAD_JSON_FILES_M_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 讀取檔案庫.
        /// </summary>
        public static string JE_RUN_LOAD_JSON_FILES_TITLE {
            get {
                return ResourceManager.GetString("JE_RUN_LOAD_JSON_FILES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案新建失敗:&quot;{0}&quot;.
        /// </summary>
        public static string JE_RUN_NEW_JSON_FILE_M_2 {
            get {
                return ResourceManager.GetString("JE_RUN_NEW_JSON_FILE_M_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開新檔案.
        /// </summary>
        public static string JE_RUN_NEW_JSON_FILE_TITLE {
            get {
                return ResourceManager.GetString("JE_RUN_NEW_JSON_FILE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已在&quot;{0}&quot;新建檔案庫.
        /// </summary>
        public static string JE_RUN_NEW_JSON_FILES_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_NEW_JSON_FILES_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此文件已有現存 {0} JSON檔案，是否要清空資料夾.
        /// </summary>
        public static string JE_RUN_NEW_JSON_FILES_Q_1 {
            get {
                return ResourceManager.GetString("JE_RUN_NEW_JSON_FILES_Q_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開新檔案庫.
        /// </summary>
        public static string JE_RUN_NEW_JSON_FILES_TITLE {
            get {
                return ResourceManager.GetString("JE_RUN_NEW_JSON_FILES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 這不是一個空的資料夾，將清空所有檔案，你確定嗎?.
        /// </summary>
        public static string JE_RUN_SAVE_AS_JSON_FILES_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_SAVE_AS_JSON_FILES_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;所有檔案已存檔.
        /// </summary>
        public static string JE_RUN_SAVE_JSON_FILES_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_SAVE_JSON_FILES_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 準備掃描全部JSON檔案，根據資料重新建立JSON檔案關聯檔，會覆蓋原有的檔案關聯檔，如果JSON檔案數量眾多將會消耗很多時間，是否確定？.
        /// </summary>
        public static string JE_RUN_SCAN_JSON_FILES_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_SCAN_JSON_FILES_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}檔案掃描完畢.
        /// </summary>
        public static string JE_RUN_SCAN_JSON_FILES_M_2 {
            get {
                return ResourceManager.GetString("JE_RUN_SCAN_JSON_FILES_M_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 掃描檔案庫.
        /// </summary>
        public static string JE_RUN_SCAN_JSON_FILES_TITLE {
            get {
                return ResourceManager.GetString("JE_RUN_SCAN_JSON_FILES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欄位名稱不正確.
        /// </summary>
        public static string JE_RUN_UPDATE_COLUMN_M_1 {
            get {
                return ResourceManager.GetString("JE_RUN_UPDATE_COLUMN_M_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欄位行數不正確.
        /// </summary>
        public static string JE_RUN_UPDATE_COLUMN_M_2 {
            get {
                return ResourceManager.GetString("JE_RUN_UPDATE_COLUMN_M_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請選擇外部索引欄位.
        /// </summary>
        public static string JE_RUN_UPDATE_COLUMN_M_3 {
            get {
                return ResourceManager.GetString("JE_RUN_UPDATE_COLUMN_M_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資料表內的{0}筆資料，確定要一起更改嗎(型態不合的資料將設為初始值).
        /// </summary>
        public static string JE_RUN_UPDATE_COLUMN_M_4 {
            get {
                return ResourceManager.GetString("JE_RUN_UPDATE_COLUMN_M_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欄位&quot;{0}&quot;已更新.
        /// </summary>
        public static string JE_RUN_UPDATE_COLUMN_M_5 {
            get {
                return ResourceManager.GetString("JE_RUN_UPDATE_COLUMN_M_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新欄位.
        /// </summary>
        public static string JE_RUN_UPDATE_COLUMN_TITLE {
            get {
                return ResourceManager.GetString("JE_RUN_UPDATE_COLUMN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關於.
        /// </summary>
        public static string JE_TMI_ABOUT {
            get {
                return ResourceManager.GetString("JE_TMI_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 增加欄位.
        /// </summary>
        public static string JE_TMI_ADD_COLUMN {
            get {
                return ResourceManager.GetString("JE_TMI_ADD_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關閉檔案庫.
        /// </summary>
        public static string JE_TMI_CLOSE_ALL_FILES {
            get {
                return ResourceManager.GetString("JE_TMI_CLOSE_ALL_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關閉.
        /// </summary>
        public static string JE_TMI_CLOSE_JSON_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_CLOSE_JSON_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收縮全部.
        /// </summary>
        public static string JE_TMI_COLLAPSE_ALL {
            get {
                return ResourceManager.GetString("JE_TMI_COLLAPSE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除.
        /// </summary>
        public static string JE_TMI_DELETE_JSON_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_DELETE_JSON_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 離開.
        /// </summary>
        public static string JE_TMI_EXIT {
            get {
                return ResourceManager.GetString("JE_TMI_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 展開全部.
        /// </summary>
        public static string JE_TMI_EXPAND_ALL {
            get {
                return ResourceManager.GetString("JE_TMI_EXPAND_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案.
        /// </summary>
        public static string JE_TMI_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 語言.
        /// </summary>
        public static string JE_TMI_LANGUAGES {
            get {
                return ResourceManager.GetString("JE_TMI_LANGUAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 讀取JSON檔案庫.
        /// </summary>
        public static string JE_TMI_LOAD_JSON_FILES {
            get {
                return ResourceManager.GetString("JE_TMI_LOAD_JSON_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增JSON檔案.
        /// </summary>
        public static string JE_TMI_NEW_JSON_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_NEW_JSON_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建JSON檔案庫.
        /// </summary>
        public static string JE_TMI_NEW_JSON_FILES {
            get {
                return ResourceManager.GetString("JE_TMI_NEW_JSON_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開啟.
        /// </summary>
        public static string JE_TMI_OPEN_JSON_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_OPEN_JSON_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新命名.
        /// </summary>
        public static string JE_TMI_RENAME_JSON_FILE {
            get {
                return ResourceManager.GetString("JE_TMI_RENAME_JSON_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 另存JSON檔案庫.
        /// </summary>
        public static string JE_TMI_SAVE_AS_JSON_FILES {
            get {
                return ResourceManager.GetString("JE_TMI_SAVE_AS_JSON_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存取JSON檔案庫.
        /// </summary>
        public static string JE_TMI_SAVE_JSON_FILES {
            get {
                return ResourceManager.GetString("JE_TMI_SAVE_JSON_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 掃描JSON檔案庫.
        /// </summary>
        public static string JE_TMI_SCAN_JSON_FILES {
            get {
                return ResourceManager.GetString("JE_TMI_SCAN_JSON_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON 資料檔案編輯器.
        /// </summary>
        public static string JSON_FILE_EDITOR_TITLE {
            get {
                return ResourceManager.GetString("JSON_FILE_EDITOR_TITLE", resourceCulture);
            }
        }
    }
}
